version: "3.5"


services:
  cdk-sam-beta:
    build: ./cdk-sam-beta
    volumes:
      - ~/.aws:/aws
      - ../cdk:/app/cdk
      - ../src:/app/src
      - ../package.json:/app/package.json
      - ../tsconfig.json:/app/tsconfig.json

