version: '3.5'

services:
  eccodes:
    build:
      context: ./eccodes
    volumes:
      - ./grib2:/grib2
      - ./src:/src
    command: python /src/get-rad-tem-gsm.py '{"lat":35.6745,"lon":139.7169}'
